# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'data/.*|docs/.*'
        exclude_types: [markdown]
    -   id: end-of-file-fixer
        exclude: 'data/.*|docs/.*'
        exclude_types: [markdown]
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: doc/data/messages/
        exclude: 'data/.*|docs/.*|notebooks/.*|dependencies/.*'
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black  
        language: system
        types: [python]
- repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
           "--rcfile=tests/.pylintrc" #Link to config file > `pylint --generate-rcfile > tests/.pylintrc`
          ]
        exclude: 'data/.*|docs/.*|notebooks/.*|dependencies/.*|src/sentient/utils/.*|src/sentient/sensor_fusion/.*'
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [ text ]
        exclude: 'data/.*|docs/.*|notebooks/.*|dependencies/.*'
