name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - 46-ci-pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --color always --verbose
